# Generated by Django 4.0.1 on 2022-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertApp', '0002_alter_advert_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
