"""
Django settings for logger project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import django.utils.log

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&*w^7mfl$l&$dn@z4-)772uowo7&26h0vn0y-8)#ia1aqra!ed'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Словарь конфигурации логирования
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # Форматы выдаваемых сообщений
    'formatters': {
        # Формат для всех сообщений уровня Debug и выше, выводящихся в консоль (уровень, время, сообщение)
        'base_format': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
        # Формат сообщений Warning и выше (включает путь к источнику события pathname)
        'warning_format': {
            'format': '%(levelname)s %(asctime)s %(pathname)s %(message)s'
        },
        # Формат сообщений Error и Critical, а также для файла errors.log (содержит стек ошибок exc_info)
        'error_format': {
            'format': '%(levelname)s %(asctime)s %(pathname)s %(exc_info)s %(message)s'
        },
        # Формат сообщений для файла general.log (время, уровень, название модуля)
        'general_format': {
            'format': '%(levelname)s %(asctime)s %(module)s'
        },
        # Формат сообщений для файла security.log (время, уровень, название модуля, сообщение)
        'security_format': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        }
    },
    # Фильтры
    'filters': {
        # Фильтр для сообщений при DEBUG = true
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        # Фильтр для сообщений при DEBUG = false
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    # Обработчики сообщений
    'handlers': {
        # Вывод в консоль сообщений уровня Debug и выше (если Debug = true)
        'base_console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'base_format'
        },
        # Вывод в консоль сообщений уровня Warning и выше (если Debug = true)
        'warning_console': {
            'level': 'WARNING',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'warning_format'
        },
        # Вывод в консоль сообщений уровня Error и выше (если Debug = true)
        'error_console': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'error_format'
        },
        # Запись в файл general.log сообщений уровня Info и выше
        'general_log_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'general.log'),
            'formatter': 'general_format'
        },
        # Запись в файл errors.log сообщений уровня Error и выше
        'error_log_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'errors.log'),
            'formatter': 'error_format'
        },
        # Запись в файл security.log всех сообщений
        'security_log_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'security.log'),
            'formatter': 'security_format'
        },
        # Отправка на почту сообщений уровня Error и выше (если Debug = false)
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'warning_format'
        }
    },
    # "отлов сообщений
    'loggers': {
        # Вывод всех сообщений в консоль и запись в general.log
        # сообщений от основного логгера django
        'django': {
            'handlers': ['base_console', 'warning_console', 'error_console', 'general_log_file'],
            'propagate': True,
        },
        # Запись в errors.log и отправка по почте сообщений от django.request
        'django.request': {
            'handlers': ['error_log_file', 'mail_admins'],
            'propagate': False,
        },
        # Запись в errors.log и отправка по почте сообщений от django.server
        'django.server': {
            'handlers': ['error_log_file', 'mail_admins'],
            'propagate': False,
        },
        # Запись в errors.log сообщений от django.template
        'django.template': {
            'handlers': ['error_log_file'],
            'propagate': False,
        },
        # Запись в errors.log сообщений от django.db_backends
        'django.db_backends': {
            'handlers': ['error_log_file'],
            'propagate': False,
        },
        # Запись в security.log сообщений от django.security
        'django.security': {
            'handlers': ['security_log_file'],
            'propagate': False,
        },
    }

}

SITE_ID = 1

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # подключаем ещё приложения
    'django.contrib.sites',
    'django.contrib.flatpages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware'
]

ROOT_URLCONF = 'logger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
